### ISSUE TITLE
Add user account functionality

### ISSUE THREAD

**Issue by dennis-bor** [tsg-humlab/shewrote#8]

**Comment by vanlummelhuizen** [comment]
Similar to #14, which I finished already. Let's leave it open for the following:

@ACNMontoya now the accounts are made via the admin pages. Should we implement functionality so that people can register? If so, I assume registered users should be given edit permissions by a staff member. Correct? 
What priority should this issue get, given that we can always add account via the admin pages?

**Comment by ACNMontoya** [comment]
Adding accounts via the admin page is good enough for now, no need to create new functionality yet.
